services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo_db/data:/data/db
      - ./mongo_db/configdb:/data/configdb
      - ./mongo_db/logs:/data/logs

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 21387:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_BASICAUTH: 'true'
  neo4j:
    container_name: neo4j
    image: neo4j:community
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - TZ=America/Toronto
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: ghcr.io/jonesywolf/bitcoin-aml-thesis/worker:latest
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - mongo
      - neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      BLOCKSTREAM_API_URL: ${BLOCKSTREAM_API_URL}
      BLOCKSTREAM_RATE_LIMIT_MS: 50
      SETUP_MONGO_DB: False # Set to True to setup the MongoDB database
      APPLICATION_TYPE: WORKER
  
  api:
    image: ghcr.io/jonesywolf/bitcoin-aml-thesis/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongo
      - neo4j:
        condition: service_healthy
      - worker
    environment:
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      APPLICATION_TYPE: API